### ISSUE TITLE
JSON API

### ISSUE THREAD

**Issue by artyom-poptsov** [cadrspace/hackdepot#7]
Implement a JSON API that will allow us to interact with HackDepot bypassing the web UI.

The work on the implementation is ongoing on [wip-json-api](https://github.com/cadrspace/hackdepot/tree/wip-json-api) branch.

**Comment by artyom-poptsov** [comment]
It seems that JSON API mostly works, just merged 'wip-json-api' branch into the 'master'.

Also, there is a simple console client for HackDepot: https://github.com/cadrspace/hd

@noroot could you please check if the implementation of API is right?  The main thing I'm worried about is protection from CSRF -- I had to write this in the main `ApplicationController`:

``` ruby
  protect_from_forgery with: :null_session,
                       only: Proc.new { |c| c.request.format.json? }
```

Will it work as it should with the regular web UI?

I think the next big step will be to implement an Android client for HackDepot.

**Comment by noroot** [comment]
It is OK to disable CSRF checking in API, it should works fine i believe

**Comment by artyom-poptsov** [comment]
Alright, thanks.  Closing the issue.
